# Generated by Django 5.2.7 on 2025-10-27 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('target_reps', models.CharField(blank=True, help_text="e.g., '8' or '8-12'", max_length=20, null=True)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rest_time_after', models.PositiveIntegerField(blank=True, help_text='Rest in seconds AFTER this set', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_sets', to='exercises.exercise')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.exercisegroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workoutplan')),
            ],
        ),
        migrations.CreateModel(
            name='LoggedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('actual_reps', models.PositiveIntegerField()),
                ('actual_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actual_rest_time', models.PositiveIntegerField(blank=True, help_text='Actual rest in seconds', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_sets', to='exercises.exercise')),
                ('planned_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.plannedset')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_sets', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
