# Generated by Django 5.2.7 on 2025-10-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_plannedset_workoutsession_loggedset'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=10),
        ),
    ]
