# Generated by Django 5.2.7 on 2025-10-29 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutsession_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='status',
        ),
    ]
