# Generated by Django 5.2.7 on 2025-10-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_workoutsession_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'ordering': ['-date_started']},
        ),
        migrations.AddField(
            model_name='plannedset',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='current_group_index',
            field=models.PositiveIntegerField(default=0, help_text='Index of the current exercise group'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='current_set_index',
            field=models.PositiveIntegerField(default=0, help_text='Index of the current set within the group'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20),
        ),
    ]
