# Generated by Django 5.2.7 on 2025-10-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_workoutsession_options_plannedset_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
