# Generated by Django 5.2.7 on 2025-10-29 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_alter_workoutsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedset',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this set was completed'),
        ),
        migrations.AlterField(
            model_name='loggedset',
            name='actual_rest_time',
            field=models.PositiveIntegerField(blank=True, help_text='Calculated rest in seconds from previous set', null=True),
        ),
    ]
