# Generated by Django 5.2.7 on 2025-10-30 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_loggedset_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('owner',), name='unique_in_progress_session_for_owner'),
        ),
    ]
