# Generated by Django 5.2.7 on 2025-11-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_workoutsession_unique_in_progress_session_for_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='break_timer_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Planned break duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='break_timer_elapsed_when_paused',
            field=models.PositiveIntegerField(default=0, help_text='Elapsed seconds when paused'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='break_timer_paused_at',
            field=models.DateTimeField(blank=True, help_text='When the timer was paused (if paused)', null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='break_timer_started_at',
            field=models.DateTimeField(blank=True, help_text='When the break timer was started', null=True),
        ),
    ]
