# Generated by Django 5.2.7 on 2025-11-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_workoutsession_break_timer_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='break_timer_duration',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='break_timer_elapsed_when_paused',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='break_timer_paused_at',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='break_timer_started_at',
        ),
    ]
